### ISSUE TITLE
Corrigir create/update para casos com aspas

### ISSUE THREAD

**Issue by LeticiaTiemi** [indigotech/bot-devices#2]

**Comment by askmon** [comment]
@LeticiaTiemi Lembra do que se trata? será que é melhor fechar e esperar que o problema se manifeste novamente?

**Comment by LeticiaTiemi** [comment]
@askmon ixi... deve ser quando vc tenta colocar aspas no nome do device ou algo assim... mas se ninguém se incomodou, acho que podemos fechar por hora.

**Comment by askmon** [comment]
Nunca tivemos esse problema, acho que colocar nos docs deveria bastar
