### ISSUE TITLE
Integrar com o hubot

### ISSUE THREAD

**Issue by LeticiaTiemi** [indigotech/bot-devices#5]

**Comment by askmon** [comment]
Primeira coisa que precisa ser feita, tirar tudo isso:
https://github.com/indigotech/bot-devices/blob/master/src/bot.coffee#L27-L77

Nós vamos trocar para os métodos do hubot (temos que importar o módulo do hubot pra isso):
https://github.com/indigotech/hubot/blob/master/scripts/url-crawler.coffee#L73

Depois é preciso adaptar a resposta que deverá deixar de ser tipo isso: https://github.com/indigotech/bot-devices/blob/master/src/bot.coffee#L70
Pra ser isso:
https://github.com/indigotech/hubot/blob/master/scripts/url-crawler.coffee#L88

O último passo seria transformar em um pacote que podemos integrar ao nosso hubot como um external script. Nunca fiz isso, mas podemos observar alguns exemplos simples no npm:
https://github.com/cycomachead/hubot-meme

Pelo que entendi é só editar o package.json pra apontar um main file:
https://github.com/cycomachead/hubot-meme/blob/master/package.json#L41

**Comment by askmon** [comment]
@dandpb @LeticiaTiemi @tibawatanabe ☝️
